### Read full data

In [1]:
import pandas as pd
from pprint import pprint


ref = pd.read_csv("/Users/nident/Desktop/JOB/Cancer Cell Line Encyclopedia (CCLE)/data/pilot/KRAS_data_expanded.csv")
pprint(ref.columns)
ref.head(2)

Index(['ModelID', 'KRAS_GeneEffect', 'KRAS_expression', 'KRAS_protein_changes',
       'KRAS_hotspot', 'PatientID', 'CellLineName', 'PrimaryOrMetastasis',
       'SampleCollectionSite', 'Age', 'Sex', 'GrowthPattern'],
      dtype='str')

,ModelID,KRAS_GeneEffect,KRAS_expression,KRAS_protein_changes,KRAS_hotspot,PatientID,CellLineName,PrimaryOrMetastasis,SampleCollectionSite,Age,Sex,GrowthPattern
0,ACH-000552,-0.468224,4.958708,NaN,0,PT-sF39aT,HT-29,Primary,large_intestine,44.0,Female,Adherent
1,ACH-000958,-0.526112,4.672029,NaN,0,PT-EB6qeM,SW48,Primary,Colon,83.0,Female,Mixed

In [15]:
COAD_Model = pd.read_csv("/Users/nident/Desktop/JOB/Cancer Cell Line Encyclopedia (CCLE)/data/COAD/COAD_Model.csv")
COAD_Expression = pd.read_csv("/Users/nident/Desktop/JOB/Cancer Cell Line Encyclopedia (CCLE)/data/COAD/COAD_Expression.csv")
COAD_CRISPRGeneEffect = pd.read_csv("/Users/nident/Desktop/JOB/Cancer Cell Line Encyclopedia (CCLE)/data/COAD/COAD_CRISPRGeneEffect.csv")
COAD_Mutation = pd.read_csv("/Users/nident/Desktop/JOB/Cancer Cell Line Encyclopedia (CCLE)/data/COAD/COAD_Mutations.csv", low_memory=False)
COAD_ModelCondition = pd.read_csv("/Users/nident/Desktop/JOB/Cancer Cell Line Encyclopedia (CCLE)/data/COAD/COAD_ModelCondition.csv")


display("COAD_Model", COAD_Model.head(2))
display("COAD_Expression", COAD_Expression.head(2))
display("COAD_CRISPRGeneEffect", COAD_CRISPRGeneEffect.head(2))
display("COAD_Mutation", COAD_Mutation.head(2))
display("COAD_ModelCondition", COAD_ModelCondition.head(2))

'COAD_Model'

,ModelID,PatientID,CellLineName,StrippedCellLineName,DepmapModelType,OncotreeLineage,OncotreePrimaryDisease,OncotreeSubtype,OncotreeCode,PatientSubtypeFeatures,...,PublicComments,CCLEName,HCMIID,PediatricModelType,ModelAvailableInDbgap,ModelSubtypeFeatures,WTSIMasterCellID,SangerModelID,COSMICID,ModelIDAlias
0,ACH-000003,PT-puKIyc,CACO2,CACO2,COAD,Bowel,Colorectal Adenocarcinoma,Colon Adenocarcinoma,COAD,NaN,...,NaN,CACO2_LARGE_INTESTINE,NaN,False,Approved for public sharing - CCLE,NaN,NaN,SIDM00891,NaN,NaN
1,ACH-000007,PT-NOXwpH,LS513,LS513,COAD,Bowel,Colorectal Adenocarcinoma,Colon Adenocarcinoma,COAD,NaN,...,NaN,LS513_LARGE_INTESTINE,NaN,False,Approved for public sharing - CCLE,NaN,569.0,SIDM00677,907795.0,ACH-001078

'COAD_Expression'

,Unnamed: 0,SequencingID,ModelConditionID,ModelID,IsDefaultEntryForMC,IsDefaultEntryForModel,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
0,68,CDS-2HrGbX,MC-000999-JOmJ,ACH-000999,Yes,Yes,4.762301,0.486458,6.793519,2.585237,...,0.0,0.0,0.010904,2.002879,0.000000,0.821495,0.0,6.354614,1.04431,4.363143
1,115,CDS-46Q1Af,MC-000552-bdsQ,ACH-000552,Yes,Yes,4.092850,0.000000,7.012323,3.158833,...,0.0,0.0,0.000000,1.766875,0.015205,0.514804,0.0,6.048471,0.00000,5.173108

'COAD_CRISPRGeneEffect'

,ModelID,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),...,OR3A2 (4995),OR3A3 (8392),POLR2J (5439),PRAMEF10 (343071),PRR33 (102724536),RGPD2 (729857),SMIM10L3 (122526779),TPRX2 (503627),TTLL13 (440307),VCX2 (51480)
0,ACH-000552,0.100104,0.091508,-0.084647,0.127559,0.104604,0.037875,0.283021,-0.240823,-0.040064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACH-000958,-0.165650,0.029107,-0.058589,0.121673,0.025537,-0.276521,0.020071,-0.093698,-0.191400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

'COAD_Mutation'

,Unnamed: 0,SequencingID,ModelID,ModelConditionID,IsDefaultEntryForModel,IsDefaultEntryForMC,Chrom,Pos,Ref,Alt,...,GwasDisease,GwasPmID,GtexGene,ProveanPrediction,AMClass,AMPathogenicity,Rescue,RescueReason,Hotspot,EntrezGeneID
0,20,CDS-vHArJs,ACH-000969,MC-000969-drm8,Yes,Yes,chr1,942225,TG,GC,...,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,148398.0
1,68,CDS-kmfiCf,ACH-000957,MC-000957-Yckn,Yes,Yes,chr1,961336,GC,G,...,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,339451.0

'COAD_ModelCondition'

,ModelConditionID,ModelID,ParentModelConditionID,DataSource,CellFormat,Morphology,PassageNumber,GrowthMedia,FormulationID,PlateCoating,SerumFreeMedia,PrescreenTreatmentDrug,PrescreenTreatmentDrugDays,AnchorDrug,AnchorDrugConcentration,AnchorDaysWithDrug
0,MC-000003-DWgN,ACH-000003,NaN,BROAD,adherent,NaN,NaN,MF-015-009,EMEM + 20% FBS,NaN,False,NaN,NaN,NaN,NaN,NaN
1,MC-000007-nTml,ACH-000007,NaN,SANGER,adherent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### New DF

In [16]:
# Model
COAD_Full = COAD_Model[['ModelID', 'PatientID', 'CellLineName', 'PrimaryOrMetastasis',
                        'SampleCollectionSite', 'Age', 'Sex', 'GrowthPattern']].copy()

COAD_Full.head(2)

,ModelID,PatientID,CellLineName,PrimaryOrMetastasis,SampleCollectionSite,Age,Sex,GrowthPattern
0,ACH-000003,PT-puKIyc,CACO2,Primary,Colon,72.0,Male,Adherent
1,ACH-000007,PT-NOXwpH,LS513,Primary,large_intestine,63.0,Male,Adherent

In [19]:
# Expression
drop_col = ['Unnamed: 0', 'IsDefaultEntryForMC', 'IsDefaultEntryForModel']
COAD_Expression_2 = COAD_Expression.drop(columns=drop_col).copy()
COAD_Expression_2.head(2)

,SequencingID,ModelConditionID,ModelID,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),FIRRM (55732),FGR (2268),CFH (3075),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
0,CDS-2HrGbX,MC-000999-JOmJ,ACH-000999,4.762301,0.486458,6.793519,2.585237,3.417521,1.380325,0.049017,...,0.0,0.0,0.010904,2.002879,0.000000,0.821495,0.0,6.354614,1.04431,4.363143
1,CDS-46Q1Af,MC-000552-bdsQ,ACH-000552,4.092850,0.000000,7.012323,3.158833,3.742265,0.018586,4.539971,...,0.0,0.0,0.000000,1.766875,0.015205,0.514804,0.0,6.048471,0.00000,5.173108

In [32]:
# CRISPRGeneEffect
print(COAD_CRISPRGeneEffect.shape)
COAD_CRISPRGeneEffect_2 = COAD_CRISPRGeneEffect.dropna(axis=1, how='all').copy()
print(COAD_CRISPRGeneEffect_2.shape)

COAD_CRISPRGeneEffect_2.head(2)

(48, 18514)
(48, 18514)

,ModelID,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),...,TPTE (7179),TRIM43B (653192),TVP23B (51030),UQCRH (7388),USP17L1 (401447),USP17L2 (377630),WASHC1 (100287171),ZNF475 (100505841),ZNF705A (440077),ZNG1F (644019)
0,ACH-000552,0.100104,0.091508,-0.084647,0.127559,0.104604,0.037875,0.283021,-0.240823,-0.040064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACH-000958,-0.165650,0.029107,-0.058589,0.121673,0.025537,-0.276521,0.020071,-0.093698,-0.191400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
# Mutation
COAD_Mutation_2 = COAD_Mutation[['ModelID', 'SequencingID', 'ModelConditionID', 'ProteinChange', 'HugoSymbol', 'VariantType', 'Hotspot']].copy()
COAD_Mutation_2.head(2)

,ModelID,SequencingID,ModelConditionID,ProteinChange,HugoSymbol,VariantType,Hotspot
0,ACH-000969,CDS-vHArJs,MC-000969-drm8,p.V483G,SAMD11,substitution,False
1,ACH-000957,CDS-kmfiCf,MC-000957-Yckn,p.M53WfsTer8,KLHL17,deletion,False

In [29]:
# Clear data without CRISPRGeneEffect

print("Before filtering COAD_Full:", COAD_Full.shape)
COAD_Full = COAD_Full[COAD_Full['ModelID'].isin(COAD_CRISPRGeneEffect_2['ModelID'].unique())].copy()
print("After filtering COAD_Full:", COAD_Full.shape)

Before filtering COAD_Full: (74, 8)
After filtering COAD_Full: (48, 8)

### For each ModelID

In [37]:
limit = 2
for idx, row in COAD_Full.iterrows():
    if idx >= limit:
        break

    display(row.to_frame().T)

    def clear_df(df, model_id_col, drop_col_names):
        df = df[df[model_id_col] == row[model_id_col]]
        df = df.drop(columns=drop_col_names)
        df = df.dropna(axis=1, how='all')
        return df
    

    exp = clear_df(COAD_Expression_2, 'ModelID', ['ModelID', 'ModelConditionID', 'SequencingID'])
    display("Expression", exp.head(2))
   
    mut = clear_df(COAD_Mutation_2, 'ModelID', ['ModelID', 'ModelConditionID', 'SequencingID'])
    display("Mutation", mut.head(2))

    crispr = clear_df(COAD_CRISPRGeneEffect_2, 'ModelID', ['ModelID'])
    display("CRISPRGeneEffect", crispr.head(2))

,ModelID,PatientID,CellLineName,PrimaryOrMetastasis,SampleCollectionSite,Age,Sex,GrowthPattern
1,ACH-000007,PT-NOXwpH,LS513,Primary,large_intestine,63.0,Male,Adherent

'Expression'

,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),FIRRM (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),NFYA (4800),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
29,3.693431,0.0,6.139473,3.419419,3.979266,0.029768,0.021838,5.858349,5.4171,3.880166,...,0.0,0.082656,0.005526,1.607025,0.0,0.943968,0.0,5.528233,0.0,3.14505

'CRISPRGeneEffect'

,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),AADAC (13),...,ZWILCH (55055),ZWINT (11130),ZXDA (7789),ZXDB (158586),ZXDC (79364),ZYG11A (440590),ZYG11B (79699),ZYX (7791),ZZEF1 (23140),ZZZ3 (26009)
23,0.016785,-0.054811,0.026886,0.136228,0.055993,0.009899,0.013887,-0.369927,-0.132036,0.208374,...,-0.307659,-0.421065,-0.037205,0.214518,0.126993,-0.035735,-0.43603,0.047007,-0.287377,-0.429066

'Mutation'

    ProteinChange HugoSymbol   VariantType
291      p.R1198W       RERE           SNV
391        p.E59K     FBXO44  substitution